name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  linux:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
      GOOS: linux
      GOARCH: 386
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Tidy go modules
      run: go mod tidy

    - name: Build
      run: go build -buildmode=c-shared -o build/base.so main.go
