name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  linux:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
      GOOS: linux
      GOARCH: 386
      ACCEPT_EULA: y
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Add i386 dependencies
      run: sudo dpkg --add-architecture i386

    - name: Update system
      run: sudo apt-get update -y && sudo apt-get upgrade -y

    - name: Install dependencies
      run: sudo apt-get install -y g++-multilib

    - name: Tidy go modules
      run: go mod tidy

    - name: Build
      run: go build -buildmode=c-shared -o build/govnomod.so src/main.go
